### ISSUE TITLE
Cursor position is lost when pasting multibyte characters

### ISSUE THREAD

**Issue by kattrali** [danlucraft/redcar#55]
To reproduce:
1) Open a new edit tab
2) Type some characters
3) Move to the beginning of the document
4) Paste "味噌"

Expected result: The cursor will be after 噌

Actual result: The cursor will be later in the string

**Comment by bdares** [comment]
I've installed the current version of redcar (0.13) and still have this issue.  Has the fixed not been pushed to the rubygems repositories?
