### ISSUE TITLE
Problem with net-ftp-list when installing

### ISSUE THREAD

**Issue by GBora** [danlucraft/redcar#75]
I've encountered this problem on both Windows 7 and Linux (OpenSuse) when I try to install redcar with the command given `gem install redcar`.

I get an error  when fetching net-ftp-list-3.2.7 saying that in requires a previous installation with a version >= 0, but the gem installed just before was net-ftp-list-2.1.12 and apparently it installed.

Trying to install net-ftp-list on it's own gives the same error.

Picture attached (The exact same error shows up on OpenSuse)

Please advise.

![redcar](https://cloud.githubusercontent.com/assets/3342157/2623461/d76c0e48-bcf0-11e3-9c2c-fdef1e811192.png)

**Comment by bdares** [comment]
I have the same issue on Ubuntu 12.04.  I suspect this is more a problem with the net-ftp-list gem than with redcar.

My current workaround:

```
gem install net-ftp-list --version 3.2.6
gem install net-ftp-list --version 3.2.7
gem install redcar
```

I've opened an issue on their repo here: https://github.com/stateless-systems/net-ftp-list/issues/10

**Comment by GBora** [comment]
@bdares Thanks, that solution works for me, at least on windows, since it's a net-ftp bug and you allready added a issue there, I will close the issue here.

**Comment by robertong** [comment]
This work on Mac too.
