### ISSUE TITLE
Is anyone there?

### ISSUE THREAD

**Issue by osburn-sharp** [danlucraft/redcar#80]
Just wondering if Redcar is still active. Seems to have been stuck on v0.13 for quite some time (even on Ruby 1.8.7?) I recently moved my baseline to Ruby 2.0 and now the file tree entry for the active file is invisible. Worse still, the text is invisible when trying to rename the file.

**Comment by coralcable** [comment]
I noticed same bad behaviour. There were rumors about a rebuilding of app (mainlty due a migration from swt -> swing), but i think it's almost dead.. I still consider Redcar as the best ruby IDE. I use **RVM** so i could use redcar in system mode (arch linux has MRI 1.9.3) `rvm system do redcar` and developing for 2.0 or whatever you want.

**Comment by headius** [comment]
I think the original maintainers simply don't have time for it anymore :-( I'd love to see someone pick it up, because I liked using it too.

**Comment by danlucraft** [comment]
Hi, original author here. Thanks for your nice comments about Redcar @MinasMazar, @headius, they mean a lot to me. (@headius I didn't even realise that was you until I came here to reply :) 

No, I'm not planning to do any more work on this project. OTOH I no longer hate the sight of it like I used to, so who knows in future.

(Also 5am is for nappies now, not open source :)
