### ISSUE TITLE
/home/karther/.rvm/gems/ruby-2.4.0/gems/redcar-0.13/lib/redcar.rb:32:in `<top (required)>': uninitialized constant Config (NameError) Did you mean?  RbConfig

### ISSUE THREAD

**Issue by krthr** [danlucraft/redcar#82]
hey! i'm trying to install redcar, but when i run `ruby bin/redcar` i get this:

```bash
/home/karther/.rvm/gems/ruby-2.4.0/gems/redcar-0.13/lib/redcar.rb:32:in `<top (required)>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
```

**Comment by sarbazx** [comment]
write this add the top of the redcar.rb file:
`Config = RbConfig`

**Comment by krthr** [comment]
Thank you!

**Comment by Viper5985** [comment]
/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/lib/redcar.rb:32:in `<top (required)>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/bin/redcar:23:in `<top (required)>'
	from /Users/Viper/.rbenv/versions/2.4.2/bin/redcar:23:in `load'
	from /Users/Viper/.rbenv/versions/2.4.2/bin/redcar:23:in `<main>'

**Comment by Viper5985** [comment]
Hey I'm trying to run redcar but when I run redcar from the terminal I get this:

`/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/lib/redcar.rb:32:in` `<top (required)>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/bin/redcar:23:in `<top (required)>'
	from /Users/Viper/.rbenv/versions/2.4.2/bin/redcar:23:in `load'
	from /Users/Viper/.rbenv/versions/2.4.2/bin/redcar:23:in `<main>'

**Comment by THUFIR** [comment]
which is "the" `redcar.rb` file to modify?
```

thufir@dur:~$ 
thufir@dur:~$ pwd
/home/thufir
thufir@dur:~$ 
thufir@dur:~$ find . -name "redcar.rb"
./.rvm/gems/ruby-2.4.2/gems/redcar-0.13/lib/redcar.rb
./.rvm/gems/ruby-2.4.2/gems/redcar-0.13/plugins/redcar/redcar.rb
thufir@dur:~$ 
thufir@dur:~$ which ruby
/home/thufir/.rvm/rubies/ruby-2.4.2/bin/ruby
thufir@dur:~$ 
thufir@dur:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
thufir@dur:~$ 

```

A good line number, where to add the config, would be appreciated.

**Comment by sarbazx** [comment]
@THUFIR in your case add 
```Config = RbConfig```
into 
```./.rvm/gems/ruby-2.4.2/gems/redcar-0.13/lib/redcar.rb```
at line number 0, at the top of file redcar.rb

**Comment by sarbazx** [comment]
for @Viper5985 add that line to 
```/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/lib/redcar.rb```
file.

**Comment by Viper5985** [comment]
Thanks @sarbazx 

I made the adjustment and now I got this:

`Viper$ redcar
Redcar 0.13 ( x86_64-darwin14 )
java -XstartOnFirstThread -d32 -client -Xbootclasspath/a:/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-jruby-0.1/vendor/jruby-complete-1.6.4.jar -Dfile.encoding=UTF8 -Xmx320m -Xss1024k -Djruby.memory.max=320m -Djruby.stack.max=1024k org.jruby.Main /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/bin/redcar --no-sub-jruby --ignore-stdin --start-time=1509302393   && echo 'finished'
/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/lib/redcar.rb:1 warning: already initialized constant Config
Redcar 0.13 ( java )
RuntimeError: No 32 bit Mac OSX SWT jar available :(
   relative_jar_path at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/jar_loader.rb:17
            jar_path at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/jar_loader.rb:8
                 Swt at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/jar_loader.rb:38
              (root) at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/jar_loader.rb:3
             require at org/jruby/RubyKernel.java:1038
             require at file:/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-jruby-0.1/vendor/jruby-complete-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29
              (root) at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/jar_loader.rb:2
             require at org/jruby/RubyKernel.java:1038
             require at file:/Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-jruby-0.1/vendor/jruby-complete-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29
  load_prerequisites at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/swt-4.6.1.1/lib/swt/minimal.rb:145
       load_threaded at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/lib/redcar.rb:182
              (root) at /Users/Viper/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redcar-0.13/bin/redcar:28"

**Comment by sarbazx** [comment]
RuntimeError: No 32 bit Mac OSX SWT jar available :(
Seems you can't run redcar because as error suggests you are using 32 bit Mac OSX.

**Comment by THUFIR** [comment]
I'm still getting:
```

thufir@dur:~$ 
thufir@dur:~$ head ./.rvm/gems/ruby-2.4.2/gems/redcar-0.13/lib/redcar.rb
Config = RbConfig  #per https://github.com/danlucraft/redcar/issues/82

$:.push(File.expand_path(File.join(File.dirname(__FILE__))))

require 'redcar/usage'

require 'redcar/ruby_extensions'
require 'redcar/instance_exec'
require 'redcar/usage'
require 'redcar/logger'
thufir@dur:~$ 
thufir@dur:~$ gem redcar
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command redcar
thufir@dur:~$ 
```


would it be useful to use git at this point?

**Comment by sarbazx** [comment]
@THUFIR don't write gem redcar, write just redcar

**Comment by THUFIR** [comment]
@sarbazx thanks.
